name: Train on main branch

on:
  push:
    branches:
      - develop

jobs:

  experiment:
    name: Run Experiment Job (Dev)
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Azure ML CLI
        run: |
          pip install azure-ai-ml
          az extension add -n ml -y

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Submit dev training job
        id: dev_job
        run: |
          az ml job create --file src/job.yml --workspace-name aml-tccc-ms-training-dts-dsml-poc --resource-group rg-tccc-ms-training-for-dts-dsml-poc

  production:
    name: Run Production Job
    runs-on: ubuntu-latest
    needs: experiment
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Azure ML CLI
        run: |
          pip install azure-ai-ml
          az extension add -n ml -y

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Submit prod training job
        run: |
          az ml job create --file src/job-prod.yml --workspace-name aml-tccc-ms-training-dts-dsml-poc --resource-group rg-tccc-ms-training-for-dts-dsml-poc
